'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/app/lib/auth/client'
import WaliLogo from '@/app/components/WaliLogo'

export default function DisclaimerPage() {
  const router = useRouter()
  const [checked, setChecked] = useState(false)
  const [loading, setLoading] = useState(false)

  const handleAccept = async () => {
    if (!checked) return
    setLoading(true)

    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()

    if (user) {
      // Record acceptance server-side
      await fetch('/api/disclaimer/accept', { method: 'POST' })
    }

    router.push('/')
    router.refresh()
  }

  return (
    <div className="min-h-screen flex flex-col items-center justify-center px-4 py-12"
      style={{ background: '#0a0d12' }}>

      {/* Logo */}
      <div className="mb-8">
        <WaliLogo size="xl" priority />
      </div>

      <div className="w-full max-w-lg rounded-2xl border overflow-hidden"
        style={{ background: '#111620', borderColor: 'rgba(255,255,255,0.08)' }}>

        {/* Header */}
        <div className="px-6 py-5 border-b" style={{ borderColor: 'rgba(255,255,255,0.07)' }}>
          <h1 className="text-lg font-bold text-white mb-1">Important Disclaimer</h1>
          <p className="text-sm text-white/40">Please read carefully before using Wali-OS</p>
        </div>

        {/* Disclaimer text */}
        <div className="px-6 py-5 space-y-4 text-sm text-white/60 leading-relaxed max-h-96 overflow-y-auto border-b"
          style={{ borderColor: 'rgba(255,255,255,0.07)' }}>

          <div>
            <h2 className="text-white/80 font-semibold mb-1.5">Not Financial Advice</h2>
            <p>Wali-OS is an informational tool only. Nothing on this platform constitutes financial advice, investment advice, trading advice, or any other type of advice. The analysis, signals, verdicts, and recommendations generated by Wali-OS are produced by artificial intelligence models and are provided for educational and informational purposes only.</p>
          </div>

          <div>
            <h2 className="text-white/80 font-semibold mb-1.5">No Guarantee of Accuracy</h2>
            <p>AI-generated analysis may be incorrect, incomplete, or outdated. Market conditions change rapidly. Technical indicators, fundamental data, and news analysis are not guarantees of future performance. Wali-OS makes no representations or warranties about the accuracy, reliability, completeness, or timeliness of any information provided.</p>
          </div>

          <div>
            <h2 className="text-white/80 font-semibold mb-1.5">Investment Risk</h2>
            <p>All investments involve risk, including the possible loss of principal. Past performance is not indicative of future results. The value of investments can go down as well as up. You should never invest money that you cannot afford to lose. You are solely responsible for any investment decisions you make.</p>
          </div>

          <div>
            <h2 className="text-white/80 font-semibold mb-1.5">No Professional Relationship</h2>
            <p>Use of Wali-OS does not create a client, advisory, fiduciary, or professional relationship of any kind between you and Wali-OS or its operators. We are not a registered investment advisor, broker-dealer, or financial planner. Before making any financial decisions, consult a qualified financial professional who understands your personal situation.</p>
          </div>

          <div>
            <h2 className="text-white/80 font-semibold mb-1.5">Data Sources</h2>
            <p>Market data is sourced from third-party providers and may be delayed, inaccurate, or unavailable. News and sentiment analysis is AI-generated and may not reflect current market conditions. Congressional trading data, SEC filings, and options flow data are sourced from public records and third-party aggregators and may not be complete or accurate.</p>
          </div>

          <div>
            <h2 className="text-white/80 font-semibold mb-1.5">Limitation of Liability</h2>
            <p>To the maximum extent permitted by applicable law, Wali-OS and its operators shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of or reliance on this platform, including but not limited to any investment losses, loss of profits, or financial harm of any kind.</p>
          </div>

          <div>
            <h2 className="text-white/80 font-semibold mb-1.5">Your Responsibility</h2>
            <p>By using Wali-OS you acknowledge that you understand these limitations, that you are using this tool at your own risk, and that all investment decisions are your own responsibility. You agree to conduct your own due diligence and consult qualified professionals before making any investment decision.</p>
          </div>
        </div>

        {/* Accept */}
        <div className="px-6 py-5 space-y-4">
          <label className="flex items-start gap-3 cursor-pointer group">
            <div className="relative mt-0.5 shrink-0">
              <input type="checkbox" checked={checked} onChange={e => setChecked(e.target.checked)}
                className="sr-only" />
              <div className="w-5 h-5 rounded border-2 transition-all flex items-center justify-center"
                style={{
                  borderColor: checked ? '#7c3aed' : 'rgba(255,255,255,0.2)',
                  background: checked ? '#7c3aed' : 'transparent'
                }}>
                {checked && <span className="text-white text-xs font-bold">âœ“</span>}
              </div>
            </div>
            <span className="text-sm text-white/60 leading-relaxed">
              I have read and understood this disclaimer. I acknowledge that Wali-OS does not provide financial advice and that I am solely responsible for any investment decisions I make.
            </span>
          </label>

          <button onClick={handleAccept} disabled={!checked || loading}
            className="w-full py-3.5 rounded-xl font-bold text-white transition-all hover:opacity-90 disabled:opacity-30 disabled:cursor-not-allowed"
            style={{ background: 'linear-gradient(135deg,#7c3aed,#4f46e5)' }}>
            {loading ? 'Continuingâ€¦' : 'I understand â€” continue to Wali-OS'}
          </button>
        </div>
      </div>
    </div>
  )
}
